export const ADD_MERGE_REQUEST = 'ADD_MERGE_REQUEST'

export const SET_FORM_ISSUE_ASSIGNEE = 'SET_FORM_ISSUE_ASSIGNEE'
export const SET_FORM_ISSUE_STATE = 'SET_FORM_ISSUE_STATE'
export const SET_FORM_ISSUE_COMMENT = 'SET_FORM_ISSUE_COMMENT'
export const SET_FORM_ISSUE_TITLE = 'SET_FORM_ISSUE_TITLE'
